# Generated by Django 4.2.3 on 2023-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_message_date_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_sent",
            field=models.DateTimeField(auto_now_add=True, max_length=32),
        ),
    ]
