# Generated by Django 4.2.3 on 2023-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_message_receiver_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="receiver_string",
            field=models.CharField(default="lol", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="sender_string",
            field=models.CharField(default="lol", max_length=32),
            preserve_default=False,
        ),
    ]
