# Generated by Django 4.2.3 on 2023-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_message_date_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="slug_subject",
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
