# Generated by Django 4.2.3 on 2023-10-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_message_read_message_slug_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(max_length=500),
        ),
    ]
