# Generated by Django 4.2.3 on 2023-09-21 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="plant",
            managers=[],
        ),
        migrations.DeleteModel(
            name="HistoricalPlant",
        ),
    ]
