# Generated by Django 4.2.3 on 2023-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0002_alter_plant_managers_delete_historicalplant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
