# Generated by Django 4.2.3 on 2023-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0008_alter_plant_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pics"),
        ),
    ]
