# Generated by Django 4.2.3 on 2023-09-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_collection", "0009_alter_plant_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
