# Generated by Django 4.2.3 on 2023-09-24 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0011_alter_plant_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="for_trade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plant",
            name="slug",
            field=models.SlugField(default="bugged-plant"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="nick_name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
