# Generated by Django 4.2.3 on 2023-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0012_plant_for_trade_plant_slug_alter_plant_nick_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="picture",
            field=models.ImageField(default="BUG", upload_to="pics"),
            preserve_default=False,
        ),
    ]
