# Generated by Django 4.2.3 on 2023-09-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0014_remove_plant_picture_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picture",
                to="plant_collection.plant",
            ),
        ),
    ]
