# Generated by Django 4.2.3 on 2023-09-30 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_collection", "0015_alter_image_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
