# Generated by Django 4.2.3 on 2023-10-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0017_alter_plant_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="slug",
            field=models.SlugField(default="bugged-species"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plants",
                to="plant_collection.species",
            ),
        ),
    ]
