# Generated by Django 4.2.3 on 2023-10-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plant_collection",
            "0021_trade_offered_finalized_trade_requested_finalized_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
