# Generated by Django 4.2.3 on 2023-10-13 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0022_alter_trade_accepted"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trade",
            unique_together={("plant_offered", "plant_requested")},
        ),
    ]
