# Generated by Django 4.2.3 on 2023-10-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0024_plant_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="location",
            field=models.CharField(
                blank=True,
                default="Unknown",
                help_text="City, State",
                max_length=64,
                null=True,
            ),
        ),
    ]
