# Generated by Django 4.2.3 on 2023-10-25 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_collection", "0027_plant_content_alter_plant_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="plant",
            new_name="planto",
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnail",
                to="plant_collection.plant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plant",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
