# Generated by Django 4.2.3 on 2023-10-25 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0028_rename_plant_image_planto_image_thumbnail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="planto",
            new_name="plant",
        ),
        migrations.RemoveField(
            model_name="image",
            name="thumbnail",
        ),
    ]
