# Generated by Django 4.2.3 on 2023-10-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plant_collection", "0029_rename_planto_image_plant_remove_image_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="plant_collection.image",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="plant_collection.plant",
                    ),
                ),
            ],
        ),
    ]
